# Generated by Django 5.0.6 on 2024-05-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('CH', '치킨'), ('CA', '카페')], max_length=2),
        ),
    ]
