# Generated by Django 5.0.6 on 2024-05-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
    ]
