# Generated by Django 5.0.6 on 2024-05-22 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=255)),
                ('hashtag_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hashtag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('hashtags', models.ManyToManyField(related_name='menu_items', to='menus.hashtag')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='hashtag',
            constraint=models.UniqueConstraint(fields=('hashtag', 'hashtag_author'), name='unique_user_hashtag'),
        ),
    ]
