# Generated by Django 4.2 on 2024-05-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_name_ko',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
