# Generated by Django 4.2 on 2024-05-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_hashtag_hashtag_en_hashtag_hashtag_ko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_zh_CN',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_name_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_name_zh_CN',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
