# Generated by Django 4.2 on 2024-05-21 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0002_alter_hashtag_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_hashtag', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
