# Generated by Django 5.0.6 on 2024-05-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_remove_hashtag_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
