# Generated by Django 5.0.6 on 2024-05-22 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_hashtag_hashtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='hashtag',
            constraint=models.UniqueConstraint(fields=('hashtag', 'hashtag_author'), name='unique_user_hashtag'),
        ),
    ]
