# Generated by Django 5.0.6 on 2024-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_menu', models.JSONField(default=list)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('A', '주문접수'), ('R', '준비중'), ('C', '준비완료')], max_length=1)),
            ],
        ),
    ]
